USE AdventureworksDW2016CTP3;
GO

SELECT  ProductKey ,
        ProductAlternateKey ,
        ProductSubcategoryKey ,
        WeightUnitMeasureCode ,
        SizeUnitMeasureCode ,
        EnglishProductName ,
        SpanishProductName ,
        FrenchProductName ,
        StandardCost ,
        FinishedGoodsFlag ,
        Color ,
        NTILE(7) OVER ( ORDER BY Color ) AS ColorNTile ,
        SafetyStockLevel ,
        ReorderPoint ,
        ListPrice ,
        Size ,
        SizeRange ,
        Weight ,
        DaysToManufacture ,
        ProductLine ,
        DealerPrice ,
        Class ,
        Style ,
        ModelName ,
        LargePhoto ,
        EnglishDescription ,
        FrenchDescription ,
        ChineseDescription ,
        ArabicDescription ,
        HebrewDescription ,
        ThaiDescription ,
        GermanDescription ,
        JapaneseDescription ,
        TurkishDescription ,
        StartDate ,
        EndDate ,
        Status
FROM    dbo.DimProduct;


SELECT  ProductKey ,
        ProductAlternateKey ,
		NTILE(7) OVER ( ORDER BY ProductAlternateKey ) AS ProductAlternateKeyNTile ,
        ProductSubcategoryKey ,
        WeightUnitMeasureCode ,
        SizeUnitMeasureCode ,
        EnglishProductName ,
        SpanishProductName ,
        FrenchProductName ,
        StandardCost ,
        FinishedGoodsFlag ,
        Color ,
        SafetyStockLevel ,
        ReorderPoint ,
        ListPrice ,
        Size ,
        SizeRange ,
        Weight ,
        DaysToManufacture ,
        ProductLine ,
        DealerPrice ,
        Class ,
        Style ,
        ModelName ,
        LargePhoto ,
        EnglishDescription ,
        FrenchDescription ,
        ChineseDescription ,
        ArabicDescription ,
        HebrewDescription ,
        ThaiDescription ,
        GermanDescription ,
        JapaneseDescription ,
        TurkishDescription ,
        StartDate ,
        EndDate ,
        Status
FROM    dbo.DimProduct;


SELECT  ProductKey ,
        ProductAlternateKey ,
        ProductSubcategoryKey ,
        WeightUnitMeasureCode ,
        SizeUnitMeasureCode ,
        EnglishProductName ,
		NTILE(7) OVER (ORDER BY EnglishProductName desc) AS EnglishProductNameNtile,        
		SpanishProductName ,
        FrenchProductName ,
        StandardCost ,
        FinishedGoodsFlag ,
        Color ,
        SafetyStockLevel ,
        ReorderPoint ,
        ListPrice ,
        Size ,
        SizeRange ,
        Weight ,
        DaysToManufacture ,
        ProductLine ,
        DealerPrice ,
        Class ,
        Style ,
        ModelName ,
        LargePhoto ,
        EnglishDescription ,
        FrenchDescription ,
        ChineseDescription ,
        ArabicDescription ,
        HebrewDescription ,
        ThaiDescription ,
        GermanDescription ,
        JapaneseDescription ,
        TurkishDescription ,
        StartDate ,
        EndDate ,
        Status
FROM    dbo.DimProduct;

SELECT  ProductKey ,
        ProductSubcategoryKey ,
        WeightUnitMeasureCode ,
        SizeUnitMeasureCode ,
        EnglishProductName ,
        SpanishProductName ,
        FrenchProductName ,
        StandardCost ,
        FinishedGoodsFlag ,
        Color ,
        ProductAlternateKey ,
        NTILE(7) OVER ( ORDER BY Color, ProductAlternateKey ) AS ColorProductNTile ,
        SafetyStockLevel ,
        ReorderPoint ,
        ListPrice ,
        Size ,
        SizeRange ,
        Weight ,
        DaysToManufacture ,
        ProductLine ,
        DealerPrice ,
        Class ,
        Style ,
        ModelName ,
        LargePhoto ,
        EnglishDescription ,
        FrenchDescription ,
        ChineseDescription ,
        ArabicDescription ,
        HebrewDescription ,
        ThaiDescription ,
        GermanDescription ,
        JapaneseDescription ,
        TurkishDescription ,
        StartDate ,
        EndDate ,
        Status
FROM    dbo.DimProduct;