
USE AdventureworksDW2016CTP3;
GO

SELECT  [ProductKey] ,
        [ProductAlternateKey] ,
        [ProductSubcategoryKey] ,
        [WeightUnitMeasureCode] ,
        [SizeUnitMeasureCode] ,
        [EnglishProductName] ,
        [SpanishProductName] ,
        [FrenchProductName] ,
        [StandardCost] ,
        [FinishedGoodsFlag] ,
        [Color] ,
        [SafetyStockLevel] ,
        MAX(SafetyStockLevel) OVER () AS MaxSafety ,
        [ReorderPoint] ,
        [ListPrice] ,
        [Size] ,
        [SizeRange] ,
        [Weight] ,
        [DaysToManufacture] ,
        [ProductLine] ,
        [DealerPrice] ,
        [Class] ,
        [Style] ,
        [ModelName] ,
        [LargePhoto] ,
        [EnglishDescription] ,
        [FrenchDescription] ,
        [ChineseDescription] ,
        [ArabicDescription] ,
        [HebrewDescription] ,
        [ThaiDescription] ,
        [GermanDescription] ,
        [JapaneseDescription] ,
        [TurkishDescription] ,
        [StartDate] ,
        [EndDate] ,
        [Status]
FROM    [dbo].[DimProduct];

SELECT  [ProductKey] ,
        [ProductAlternateKey] ,
        [ProductSubcategoryKey] ,
        [WeightUnitMeasureCode] ,
        [SizeUnitMeasureCode] ,
        [EnglishProductName] ,
        [SpanishProductName] ,
        [FrenchProductName] ,
        [StandardCost] ,
        [FinishedGoodsFlag] ,
        [Color] ,
        [SafetyStockLevel] ,
        MAX(SafetyStockLevel) OVER ( ORDER BY Color ) AS MaxSafetyOrderByColor ,
		MAX(SafetyStockLevel) OVER ( PARTITION BY Color ) AS MaxSafetyPartitionByColor ,
        [ReorderPoint] ,
        [ListPrice] ,
        [Size] ,
        [SizeRange] ,
        [Weight] ,
        [DaysToManufacture] ,
        [ProductLine] ,
        [DealerPrice] ,
        [Class] ,
        [Style] ,
        [ModelName] ,
        [LargePhoto] ,
        [EnglishDescription] ,
        [FrenchDescription] ,
        [ChineseDescription] ,
        [ArabicDescription] ,
        [HebrewDescription] ,
        [ThaiDescription] ,
        [GermanDescription] ,
        [JapaneseDescription] ,
        [TurkishDescription] ,
        [StartDate] ,
        [EndDate] ,
        [Status]
FROM    [dbo].[DimProduct];

SELECT  [ProductKey] ,
        [ProductAlternateKey] ,
        [ProductSubcategoryKey] ,
        [WeightUnitMeasureCode] ,
        [SizeUnitMeasureCode] ,
        [EnglishProductName] ,
        [SpanishProductName] ,
        [FrenchProductName] ,
        [StandardCost] ,
        [FinishedGoodsFlag] ,
        [Color] ,
        [SafetyStockLevel] ,
        MAX(SafetyStockLevel) OVER ( PARTITION BY Color ) AS MaxSafetyPartitionByColor ,
        MIN(SafetyStockLevel) OVER ( PARTITION BY Color ) AS MinSafetyPartitionByColor ,
        AVG(SafetyStockLevel) OVER ( PARTITION BY Color ) AS AvgSafetyPartitionByColor ,
        SUM(SafetyStockLevel) OVER ( PARTITION BY Color ) AS SumSafetyPartitionByColor ,
        COUNT(SafetyStockLevel) OVER ( PARTITION BY Color ) AS CountSafetyPartitionByColor ,
        STDEV(SafetyStockLevel) OVER ( PARTITION BY Color ) AS StDevSafetyPartitionByColor ,
        STDEVP(SafetyStockLevel) OVER ( PARTITION BY Color ) AS StDevPSafetyPartitionByColor ,
        VAR(SafetyStockLevel) OVER ( PARTITION BY Color ) AS VarSafetyPartitionByColor ,
        VARP(SafetyStockLevel) OVER ( PARTITION BY Color ) AS VarPSafetyPartitionByColor ,
        [ReorderPoint] ,
        [ListPrice] ,
        [Size] ,
        [SizeRange] ,
        [Weight] ,
        [DaysToManufacture] ,
        [ProductLine] ,
        [DealerPrice] ,
        [Class] ,
        [Style] ,
        [ModelName] ,
        [LargePhoto] ,
        [EnglishDescription] ,
        [FrenchDescription] ,
        [ChineseDescription] ,
        [ArabicDescription] ,
        [HebrewDescription] ,
        [ThaiDescription] ,
        [GermanDescription] ,
        [JapaneseDescription] ,
        [TurkishDescription] ,
        [StartDate] ,
        [EndDate] ,
        [Status]
FROM    [dbo].[DimProduct];

SELECT  [ProductKey] ,
        [ProductAlternateKey] ,
        [ProductSubcategoryKey] ,
        [WeightUnitMeasureCode] ,
        [SizeUnitMeasureCode] ,
        [EnglishProductName] ,
        [SpanishProductName] ,
        [FrenchProductName] ,
        [StandardCost] ,
        [FinishedGoodsFlag] ,
        [Color] ,
        [SafetyStockLevel] ,
        MAX(SafetyStockLevel) OVER ( PARTITION BY Color ) - MIN(SafetyStockLevel) OVER ( PARTITION BY Color ) AS DiffSafetyPartitionByColor ,
        AVG(SafetyStockLevel) OVER ( PARTITION BY Color ) AS AvgSafetyPartitionByColor ,
        SUM(SafetyStockLevel) OVER ( PARTITION BY Color ) / COUNT(SafetyStockLevel) OVER ( PARTITION BY Color ) AS SumDivCountSafetyPartitionByColor ,
        [ReorderPoint] ,
        MAX(SafetyStockLevel) OVER ( PARTITION BY Color ) - MIN(ReorderPoint) OVER ( PARTITION BY Color ) AS DiffSafetyReorderPartitionByColor ,
        [ListPrice] ,
        [Size] ,
        [SizeRange] ,
        [Weight] ,
        [DaysToManufacture] ,
        [ProductLine] ,
        [DealerPrice] ,
        [Class] ,
        [Style] ,
        [ModelName] ,
        [LargePhoto] ,
        [EnglishDescription] ,
        [FrenchDescription] ,
        [ChineseDescription] ,
        [ArabicDescription] ,
        [HebrewDescription] ,
        [ThaiDescription] ,
        [GermanDescription] ,
        [JapaneseDescription] ,
        [TurkishDescription] ,
        [StartDate] ,
        [EndDate] ,
        [Status]
FROM    [dbo].[DimProduct];



